version: '2'
services:
  a:
    image: tutum/hello-world
    container_name: eh
    networks:
      frontend:
        aliases:
          - web
  b:
    image: tutum/hello-world
    networks:
      frontend:
        aliases:
          - web
      backend:
        aliases:
          - website
  c:
    image: tutum/hello-world
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
