version: '2'
services:
  a:
    image: tutum/hello-world
    networks:
      - frontend
    links:
      - b:bee
      - c:cee
  b:
    image: tutum/hello-world
    networks:
      - frontend
      - backend
  c:
    image: tutum/hello-world
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
